language: php
php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
install: composer install

services:
  - mysql

before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS test;" -uroot

env:
  - DB_HOST=localhost DB_DATABASE=test DB_USERNAME=travis DB_PASSWORD=