language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
install: composer install

before_install:
  - mysql -e "create database IF NOT EXISTS test;" -uroot

env:
  - DB_HOST=localhost DB_DATABASE=test DB_USERNAME=travis DB_PASSWORD=