#! /usr/bin/env php

<?php

use Petrol\Core\Commands\FillCommand\ConsoleFill;
use Petrol\Core\Commands\MakeCommand\ConsoleMake;
use Petrol\Core\Commands\NewCommand\ConsoleNew;
use Symfony\Component\Console\Application;

if (file_exists('vendor/autoload.php')) {
    require 'vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    echo 'No autoloader found.';
    exit();
}

if (file_exists('.env')) {
    Dotenv::load(__DIR__);
}

$app = new Application('Petrol', '0.9.1');

$app->add(new ConsoleFill());
$app->add(new ConsoleMake());
$app->add(new ConsoleNew());

$app->run();
