#! /usr/bin/env php

<?php

use Petrol\Core\Commands\FillCommand\ConsoleFill;
use Petrol\Core\Commands\MakeCommand\ConsoleMake;
use Petrol\Core\Commands\NewCommand\ConsoleNew;
use Symfony\Component\Console\Application;
use Symfony\Component\Filesystem\Filesystem;

if (file_exists('vendor/autoload.php')) {
    require 'vendor/autoload.php';
} elseif (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    echo 'No autoloader found.';
    exit();
}

if (file_exists('.env')) {
    Dotenv::load(__DIR__);
}

$filesystem = new Filesystem();

$app = new Application('Petrol', '0.9.3');

$app->add(new ConsoleFill($filesystem));
$app->add(new ConsoleMake($filesystem));
$app->add(new ConsoleNew($filesystem));

$app->run();
